PROJECT_NAME := esp-app

# Add new components to add the KConfig of the esp32_drivers
EXTRA_COMPONENT_DIRS := components/lvgl_esp32_drivers/lvgl_tft components/lvgl_esp32_drivers/lvgl_touch 
#components/esp32-wifi-manager

include $(IDF_PATH)/make/project.mk